### PR TITLE
Dark Mode

### PR DESCRIPTION
**Pull request by alexpana**
Hello,

I wanted to improve the design of the frontend a bit, but I got carried away and I ended up adding a bunch of features. It's my first time using svelte so instead of adding features incrementally (and having separate commits), I experimented all over the place and I got a big commit.

Initially, I wanted to add dynamic support for changing light / dark theme using CSS queries, but I couldn't get chrome to enable light mode, so I postponed implementing it.

Here's a list of all the changes:

* Change theme to dark mode, colors taken from ziglang.org
* Sort packages by name
* Remove some CSS relative positioning in favor of flexbox
* Limit width to 1280px
* Add new logo based on ziglang logo
* Merge search input with the nav bar
* Add shortcut "Press 's' to search" to the search input
* Compacted tabs
* Add copy to clipboard button
* Add /author route to filter packages based on author
* Add gray icons for github / gitlab / sr.ht / git
* Change code colorscheme to match ziglang.org

### CODE REVIEW

**Comment by alexpana** [comment]
Some screenshots:

screenshot_0
screenshot_1

**Review by SuperAuguste — CHANGES_REQUESTED** [review]
This looks amazing - fantastic work! This was also my first time using Svelte and you clearly did a better job than me 😄!

Everything looks good except one small bug: when using the search bar on a page that isn't the package listing page, the package listing page isn't focused so you can't see the search results.

**Comment by SuperAuguste** [comment]
Oh, and I noticed another small thing - the ziglang.org code block theming doesn't really work on darkmode as the gray just blends in with the dark background (see attached image). I'll leave this one up to you!

image

**Comment by alexpana** [comment]
> Oh, and I noticed another small thing - the ziglang.org code block theming doesn't really work on darkmode as the gray just blends in with the dark background (see attached image). I'll leave this one up to you!

Do you by any chance have "light" mode enabled? I only added media queries for the code highlighting, and light mode uses the same color scheme as before. On dark mode this is what I get:

screenshot_3

**Comment by alexpana** [comment]
> Everything looks good except one small bug: when using the search bar on a page that isn't the package listing page, the package listing page isn't focused so you can't see the search results.

Yes, I know about it. I somehow hoped it wasn't a big deal, but I should be able to switch the page when you search.

**Comment by alexpana** [comment]
In the meantime, I found a way to switch to the light browser theme, so I'll improve the CSS to work with both.

Also, any input on the logo? I don't want to impose, and I didn't check the copyright on the zig logo, but I think it definitely looks better with a logo than with the text.

**Comment by SuperAuguste** [comment]
> Do you by any chance have "light" mode enabled? I only added media queries for the code highlighting, and light mode uses the same color scheme as before. On dark mode this is what I get:

Yeah, my browser's theme is indeed light mode - I guess it's a little confusing to have a dark theme page with a light theme code block when light theme is selected but it isn't that big of a deal.

> Also, any input on the logo? I don't want to impose, and I didn't check the copyright on the zig logo, but I think it definitely looks better with a logo than with the text.

I love the logo and totally agree with you. Any thoughts @MasterQ32?

**Comment by ikskuh** [comment]
> > Also, any input on the logo? I don't want to impose, and I didn't check the copyright on the zig logo, but I think it definitely looks better with a logo than with the text.
> 
> I love the logo and totally agree with you. Any thoughts @MasterQ32?

I absolutely love the logo! @alexpana, many thanks for this great PR! The changes look absolutely awesome

**Comment by alexpana** [comment]
Light mode WIP:

light01
light02

> small bug: when using the search bar on a page that isn't the package listing page, the package listing page isn't focused so you can't see the search results.

I'm having some issues keeping the search input focused when navigating to the package list page, so it may take a while.

**Comment by alexpana** [comment]
The last commit fixes the issue with searching from a page other than the package list.

**Review by SuperAuguste — APPROVED** [review]

**Comment by SuperAuguste** [comment]
This looks good, thanks! Merging now!

**Comment by alexpana** [comment]
Yay, thank you!

I just found a bug that scales the github icon on the package page each time you resize the window. I'll try to fix it today.

**Pull request merged**
